"""Eksik alanlar eklendi: seating_types.icon, event_seatings.color_code, reservations.number_of_people, cancelled_at, cancelled_by

Revision ID: 373939c82f65
Revises: ce531172fd61
Create Date: 2025-11-08 08:11:20.826430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373939c82f65'
down_revision = 'ce531172fd61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_seatings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_code', sa.String(length=7), nullable=True))

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_people', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['cancelled_by'], ['id'])

    with op.batch_alter_table('seating_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seating_types', schema=None) as batch_op:
        batch_op.drop_column('icon')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cancelled_by')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('number_of_people')

    with op.batch_alter_table('event_seatings', schema=None) as batch_op:
        batch_op.drop_column('color_code')

    # ### end Alembic commands ###
