"""add_visual_seating_dimensions

Revision ID: af16c8726fa9
Revises: 373939c82f65
Create Date: 2025-11-08 09:15:01.329445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af16c8726fa9'
down_revision = '373939c82f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_seatings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('width', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('color_code', sa.String(length=7), nullable=True))

    with op.batch_alter_table('seating_layout_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canvas_width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('canvas_height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('grid_size', sa.Integer(), nullable=True))

    with op.batch_alter_table('seating_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seating_types', schema=None) as batch_op:
        batch_op.drop_column('icon')

    with op.batch_alter_table('seating_layout_templates', schema=None) as batch_op:
        batch_op.drop_column('grid_size')
        batch_op.drop_column('canvas_height')
        batch_op.drop_column('canvas_width')

    with op.batch_alter_table('event_seatings', schema=None) as batch_op:
        batch_op.drop_column('color_code')
        batch_op.drop_column('height')
        batch_op.drop_column('width')

    # ### end Alembic commands ###
