"""Make stage_position and configuration nullable in seating templates

Revision ID: ce531172fd61
Revises: fa36f52e19d4
Create Date: 2025-11-07 23:34:55.796009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce531172fd61'
down_revision = 'fa36f52e19d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seating_layout_templates', schema=None) as batch_op:
        batch_op.alter_column('stage_position',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('configuration',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seating_layout_templates', schema=None) as batch_op:
        batch_op.alter_column('configuration',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('stage_position',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
