"""Add stage_config and canvas dimensions to events

Revision ID: fa36f52e19d4
Revises: 
Create Date: 2025-11-07 23:07:19.021337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa36f52e19d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage_config', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('canvas_width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('canvas_height', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('canvas_height')
        batch_op.drop_column('canvas_width')
        batch_op.drop_column('stage_config')

    # ### end Alembic commands ###
